aliases:
  - &run_yarn_install
    name: Install dependencies
    command: yarn install --immutable-cache

node_v10: &node_lts
  working_directory: ~/search-insights
  docker:
    - image: cimg/node:lts

version: 2
jobs:
  "build and size":
    <<: *node_lts
    steps:
      - checkout
      - run: *install_yarn_version
      - run: *run_yarn_install
      - run:
          name: Build & Test packages size
          command: |
            yarn run build
            yarn run test:size

  lint:
    <<: *node_lts
    steps:
      - checkout
      - run: *install_yarn_version
      - run: *run_yarn_install
      - run:
          name: Lint & Code styles
          command: yarn run lint
      - run:
          name: Type Checking
          command: yarn run type-check

  "release if needed":
    <<: *node_lts
    steps:
      - checkout
      - run: *install_yarn_version
      - run: *run_yarn_install
      - run:
          name: Trigger a release if the latest commit is a release commit
          command: |
            yarn shipjs trigger

  "prepare release":
    <<: *node_lts
    steps:
      - checkout
      - run: *install_yarn_version
      - run: *run_yarn_install
      - run:
          name: Prepare release
          command: |
            git config --global user.email "algobot@users.noreply.github.com"
            git config --global user.name "algobot"
            yarn run release --yes --no-browse

workflows:
  version: 2
  ci:
    jobs:
      - build and size
      - unit tests
      - lint
      - "release if needed":
          filters:
            branches:
              only:
                - master
  prepare_release_every_tuesday:
    triggers:
      - schedule:
          cron: "0 9 * * 2"
          filters:
            branches:
              only:
                - master
    jobs:
      - prepare release
